spring:
  application:
    name: groupbils
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/groupbills-db;AUTO_SERVER=TRUE;
    username: sa
  sql:
    init:
      mode: always
logging:
  level:
    org.springframework.jdbc: debug
