###
POST http://localhost:8080/signup
Content-Type: application/json

{
  "loginId": "member1",
  "name": "membername1",
  "password": "1234"
}

###
GET http://localhost:8080/members

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "loginId": "member1",
  "password": "1234"
}

###
POST http://localhost:8080/logout
Content-Type: application/json
